name: nutricare
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  youtube_player_flutter: ^9.1.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  geocoding: ^3.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - images/
    - images/food_category/
    - images/user_profile/
  uses-material-design: true